# Generated by Django 5.2.5 on 2025-08-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_query', models.CharField(max_length=100)),
                ('classification', models.CharField(max_length=100)),
            ],
        ),
    ]
